url: https://www.samipiercy.com
baseurl: 

# Site settings
title: Sami Piercy
email: Use the Contact Form!
description: "Sami Piercy, Industrial Designer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-bg: fff
  secondary-bg: f3f3f3
  primary-text: 333
  secondary-text: fff
  accent: f36b5b
  accent-rgb: 243, 107, 91
  accent-light: ffa38f
  accent-dark: b6342e

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/samanthapiercy
#  - title: behance
#    url:


# Build settings
markdown: kramdown
permalink: pretty